name: "YouTube AdBlock Plus" 
author: "Arturo + Clara"
description: Measuring youtube with AdBlock Plus
version: 1

services:
  browser-client:
    image: prueba-youtube
    build:
      context: .
    command: sleep infinity

flow:
  - name: PlayVideo
    container: browser-client
    commands:
      - type: console
        command: python measure_ytb_AdBlockPlus.py
        note: "laying YouTube video"
        read-notes-stdout: true   # enables timestamp reading